/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Memory region: heap
 * Bug type: double-free, used-memory
 * Access type: stdlib, write
 * Variant:
 *  - without use-after-free
 */

#include <unistd.h> // _exit
#include <stdint.h> // SIZE_MAX
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types

// globals


int f()
{
  // locals


  #ifndef __GLIBC__
  exit(PRECONDITIONS_FAILED_VALUE); // not using glibc
  #endif
  char *pointer_to_double_free; // pointer to be double-freed
  char *pointer_to_use; // pointer to illegally use
  char *tmp, *tmp2, *tmp3;
  tmp = (char *)malloc(8);
  tmp2 = (char *)malloc(8);
  pointer_to_double_free = (char *)malloc(8);
  free(pointer_to_double_free);
  free(tmp); // no use after free required
  pointer_to_use = (char *)malloc(8); // allocate a new object
  tmp3 = (char *)malloc(8);
  _use(tmp2);
  _use(tmp3);
  char *target = (char *)malloc( 8 );
  
  memset( (void *)pointer_to_use, 0xFF, 8);
  _use(pointer_to_use);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  free(target);
  return 0;
}

int main()
{
  f();

  return 0;
}
