/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Memory region: heap
 * Bug type: double-free, used-memory
 * Access type: direct, read
 * Variant:
 *  - without use-after-free
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

__attribute__((section(".data.index"))) volatile size_t _sink;
volatile void *_use(volatile void *p) { _sink = (size_t)p; return p; }
volatile long long _use_value(volatile long long p) { return p; }
__attribute__((noinline)) static size_t _hide_value(volatile size_t n) { volatile size_t v = n; return v; }
const char content[8] = "ZZZZZZZ";

// types

// globals


__attribute__((noinline)) int f()
{
  // locals


  #ifndef __GLIBC__
  _exit(PRECONDITIONS_FAILED_VALUE); // not using glibc
  #endif
  char *pointer_to_double_free; // pointer to be double-freed
  char *pointer_to_use; // pointer to illegally use
  char *tmp, *tmp2, *tmp3;
  tmp = (char *)malloc(8);
  tmp2 = (char *)malloc(8);
  pointer_to_double_free = (char *)malloc(8);
  _use(pointer_to_double_free);
  free(pointer_to_double_free);
  _use(tmp);
  free(tmp); // no use after free required
  pointer_to_use = (char *)malloc(8); // allocate a new object
  tmp3 = (char *)malloc(8);
  _use(tmp2);
  _use_value(*tmp2);
  _use(tmp3);
  _use_value(*tmp3);
  volatile char *target = (char *)malloc( 8 );
  
  volatile char read_value[8];
  volatile size_t i;
  for (i = 0; i < 8; i++)
  {
    read_value[i] = pointer_to_use[i];
    _use(&pointer_to_use[i]);
  }
  _use(read_value);
  _use_value(*read_value);
  exit(TEST_CASE_SUCCESSFUL_VALUE);

  free( (void *)target );
  return 0;
}

int main()
{
  f();

  return 0;
}
