/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

#include <unistd.h> // _exit
#include <stdint.h> // SIZE_MAX
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types

// globals


int f()
{
  // locals


  #ifndef __GLIBC__
  exit(PRECONDITIONS_FAILED_VALUE); // not using glibc
  #endif
  char *pointer_to_double_free; // pointer to be double-freed
  char *pointer_to_use; // pointer to illegally use
  pointer_to_double_free = (char *)malloc(10);
  free(pointer_to_double_free);
  pointer_to_use = (char *)malloc(8); // allocate a new object
  char *target = (char *)malloc( 8 );
  
  volatile char read_value[8];
  memcpy( (void *)read_value, pointer_to_use, 8);
  _use( read_value );
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  free(target);
  return 0;
}

int main()
{
  f();

  return 0;
}
