/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: global
 * Target: global
 * Bug type: intra-object, linear OOBA, overflow
 * Access type: direct, write
 * Variant: target declared after origin, target reached by writing using an index, global auxiliary variables, declared last
 */

#include <unistd.h> // _exit
#include <stdint.h> // SIZE_MAX
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types
struct T
{
  char origin[8];
  char target[8];
};

// globals

struct T s = { {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA}, {0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB} };
ssize_t reach_index = 0;

int f()
{
  // locals


  _use(s.target);
  _use(s.origin);
  while( GET_ADDR_BITS(&s.target[reach_index]) != GET_ADDR_BITS(s.target) )
  {
    s.target[reach_index] = 0xFF;
    ++reach_index;
    _use(&s.target[reach_index]);
  }
  volatile size_t i;
  for (i = 0; i < 8; i++)
  {
    (s.target + reach_index)[i] = 0xFF;
  }
  _use((s.target + reach_index));
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
