/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: stack
 * Target: global
 * Bug type: inter-object, linear OOBA, overflow
 * Access type: direct, write
 * Variant: target declared after origin, distance is checked as it is, target reached by writing using an auxiliary pointer, target accessed by writing using constants, global auxiliary variables, initialized, declared first
 */

#include <unistd.h> // _exit
#include <stdint.h> // SIZE_MAX
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types

// globals
volatile char * aux_ptr = 0;

char target[8] = {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA};

int f()
{
  // locals

  char origin[8] = "";

  origin[0] = 0xAA;
  origin[1] = 0xAA;
  origin[2] = 0xAA;
  origin[3] = 0xAA;
  origin[4] = 0xAA;
  origin[5] = 0xAA;
  origin[6] = 0xAA;
  origin[7] = 0xAA;
  _use(target);
  _use(origin);
  if ( !((ssize_t)(GET_ADDR_BITS(target) - GET_ADDR_BITS(origin)) >= 0) ) _exit(PRECONDITIONS_FAILED_VALUE);
  if ( GET_ADDR_BITS(&aux_ptr) < GET_ADDR_BITS(target) && GET_ADDR_BITS(&aux_ptr) > GET_ADDR_BITS(origin) ) _exit(PRECONDITIONS_FAILED_VALUE);
  aux_ptr = origin;
  while( GET_ADDR_BITS(aux_ptr) != GET_ADDR_BITS(target) )
  {
    *aux_ptr = 0xFF;
    ++aux_ptr;
    _use(aux_ptr);
  }
  volatile size_t i;
  for (i = 0; i < 8; i++)
  {
    aux_ptr[i] = 0xFF;
  }
  _use(aux_ptr);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
