/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: global
 * Target: global
 * Bug type: intra-object, linear OOBA, overflow
 * Access type: stdlib, write
 * Variant:
 *  - target declared after origin
 *  - target reached using a index
 */

#include <unistd.h> // _exit
#include <stdint.h> // SIZE_MAX
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types
struct T
{
  char origin[8];
  char target[8];
};

// globals

struct T s = { {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA}, {0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB} };
__attribute__((section(".data.index"))) volatile ssize_t i = 0;
__attribute__((section(".data.index"))) volatile size_t step_distance;

int f()
{
  // locals


  _use(s.target);
  _use(s.origin);
  i = 0;
  while( GET_ADDR_BITS(&s.target[i]) < GET_ADDR_BITS(s.target) )
  {
    step_distance = (GET_ADDR_BITS(s.target) > (1024 + GET_ADDR_BITS(&s.target[i]))) ? 1024 : GET_ADDR_BITS(s.target) - GET_ADDR_BITS(&s.target[i]);
    memset((void *)&s.target[i], 0xFF, step_distance);
    i += step_distance;
    _use(&s.target[i]);
  }
  _use(s.target);
  memset( (void *)&s.target[i], 0xFF, 8);
  _use(&s.target[i]);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
