/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: global
 * Target: global
 * Bug type: inter-object, linear OOBA, overflow
 * Access type: stdlib, read
 * Variant:
 *  - target declared after origin
 *  - distance is negated before checking
 *  - target reached by using a global index
 *  - target accessed by using auxiliary variables
 */

#include <unistd.h> // _exit
#include <stdint.h> // SIZE_MAX
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types

// globals

char origin[8] = {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA};
char target[8] = {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA};
volatile ssize_t i = 0;

int f()
{
  // locals


  _use(target);
  _use(origin);
  if ( !(-(ssize_t)(GET_ADDR_BITS(origin) - GET_ADDR_BITS(target)) >= 0) ) _exit(PRECONDITIONS_FAILED_VALUE);
  while( i < -(ssize_t)(GET_ADDR_BITS(origin) - GET_ADDR_BITS(target)) )
  {
    volatile char read_value[1024];
    size_t step_distance = (-(ssize_t)(GET_ADDR_BITS(origin) - GET_ADDR_BITS(target)) > (1024 + i)) ? 1024 : -(ssize_t)(GET_ADDR_BITS(origin) - GET_ADDR_BITS(target)) - i;
    memcpy((void *)read_value, (void *)&origin[i], step_distance);
    i += step_distance;
    _use(&read_value);
  }
  volatile char read_value[8];
  memcpy( (void *)read_value, (void *)&origin[i], 8);
  _use( read_value );
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
