/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.3.
 */

/*
 * Origin: global
 * Target: global
 * Bug type: inter-object, linear OOBA, overflow
 * Access type: stdlib, read
 * Variant:
 *  - target declared before origin
 *  - distance is negated before checking
 *  - target reached by using a auxiliary pointer
 *  - target accessed by using auxiliary variables
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

__attribute__((section(".data.index"))) volatile size_t _sink;
volatile void *_use(volatile void *p) { _sink = (size_t)p; return p; }
volatile long long _use_value(volatile long long p) { return p; }
__attribute__((noinline)) static size_t _hide_value(volatile size_t n) { volatile size_t v = n; return v; }
const char content[8] = "ZZZZZZZ";

// types

// globals

volatile char target[8] = {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA};
volatile char origin[8] = {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA};
__attribute__((section(".data.index"))) volatile char * aux_ptr;
__attribute__((section(".data.index"))) volatile size_t i = 0;

__attribute__((noinline)) int f()
{
  // locals


  _use(target);
  _use_value(*target);
  _use(origin);
  _use_value(*origin);
  if ( !(-(ssize_t)(GET_ADDR_BITS(origin) - GET_ADDR_BITS(target)) >= 0) ) _exit(PRECONDITIONS_FAILED_VALUE);
  aux_ptr = origin;
  while( i < -(ssize_t)(GET_ADDR_BITS(origin) - GET_ADDR_BITS(target)) )
  {
    volatile char read_value[1024];
    size_t step_distance = (-(ssize_t)(GET_ADDR_BITS(origin) - GET_ADDR_BITS(target)) > (1024 + i)) ? 1024 : -(ssize_t)(GET_ADDR_BITS(origin) - GET_ADDR_BITS(target)) - i;
    memcpy((void *)read_value, (void *)aux_ptr, _hide_value(step_distance));
    aux_ptr += step_distance;
    i += step_distance;
    _use(read_value);
    _use_value(*read_value);
  }
  volatile char read_value[8];
  memcpy( (void *)read_value, (void *)aux_ptr, _hide_value(8));
  _use( read_value );
  _use_value( *read_value );
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
