/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

#include <unistd.h> // _exit
#include <stdint.h> // SIZE_MAX
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types

// globals

char origin[8] = {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA};

int f()
{
  // locals

  char target[8] = "";
  volatile ssize_t i = 0;
  volatile size_t step_distance;

  target[0] = 0xAA;
  target[1] = 0xAA;
  target[2] = 0xAA;
  target[3] = 0xAA;
  target[4] = 0xAA;
  target[5] = 0xAA;
  target[6] = 0xAA;
  target[7] = 0xAA;
  _use(target);
  _use(origin);
  i = 0;
  while( GET_ADDR_BITS(&target[i]) < GET_ADDR_BITS(target) )
  {
    step_distance = (GET_ADDR_BITS(target) > (1024 + GET_ADDR_BITS(&target[i]))) ? 1024 : GET_ADDR_BITS(target) - GET_ADDR_BITS(&target[i]);
    memset(&target[i], 0xFF, step_distance);
    i += step_distance;
    _use(&target[i]);
  }
  _use(target);
  memset( &target[i], 0xFF, 8);
  _use(&target[i]);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
