/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.3.
 */

/*
 * Origin: heap
 * Target: global
 * Bug type: inter-object, linear OOBA, underflow
 * Access type: direct, write
 * Variant:
 *  - target declared after origin
 *  - distance is negated before checking
 *  - To avoid optimizations, index into the target
 *  - target reached by using a index
 *  - target accessed by using constants
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

__attribute__((section(".data.index"))) volatile size_t _sink;
volatile void *_use(volatile void *p) { _sink = (size_t)p; return p; }
volatile long long _use_value(volatile long long p) { return p; }
__attribute__((noinline)) static size_t _hide_value(volatile size_t n) { volatile size_t v = n; return v; }
const char content[8] = "ZZZZZZZ";

// types

// globals

volatile char target[8] = {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA};
__attribute__((section(".data.index"))) volatile ssize_t reach_index = 0;

__attribute__((noinline)) int f()
{
  // locals


  volatile char *origin = (char *)malloc( 8 );
  origin[0] = 0xAA;
  origin[1] = 0xAA;
  origin[2] = 0xAA;
  origin[3] = 0xAA;
  origin[4] = 0xAA;
  origin[5] = 0xAA;
  origin[6] = 0xAA;
  origin[7] = 0xAA;
  // index into the target to prevent optimizations
  for (ssize_t i = 0; i < _hide_value(8); i++) { char tmp = target[i]; _use(&tmp); }
  _use(target);
  _use_value(*target);
  _use(origin);
  _use_value(*origin);
  if ( GET_ADDR_BITS(&reach_index) < GET_ADDR_BITS(origin) && GET_ADDR_BITS(&reach_index) > GET_ADDR_BITS(target) ) _exit(PRECONDITIONS_FAILED_VALUE);
  if ( !(-(ssize_t)(GET_ADDR_BITS(origin) - GET_ADDR_BITS(target)) <= 0) ) _exit(PRECONDITIONS_FAILED_VALUE);
  while( GET_ADDR_BITS(&origin[reach_index]) != GET_ADDR_BITS(target) )
  {
    origin[reach_index] = 0xFF;
    --reach_index;
    _use(&origin[reach_index]);
    _use_value(origin[reach_index]);
  }
  volatile size_t i;
  for (i = 0; i < 8; i++)
  {
    (origin + reach_index)[i] = 0xFF;
    _use(&(origin + reach_index)[i]);
  }
  _use((origin + reach_index));
  _use_value(*(origin + reach_index));
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  free( (void *)origin );
  return 0;
}

int main()
{
  f();

  return 0;
}
