/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: stack
 * Target: stack
 * Bug type: non-object, linear OOBA, overflow
 * Access type: stdlib, read
 * Variant:
 *  - target reached using a index
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

__attribute__((section(".data.index"))) volatile size_t _sink;
volatile void *_use(volatile void *p) { _sink = (size_t)p; return p; }
volatile long long _use_value(volatile long long p) { return p; }
__attribute__((noinline)) static size_t _hide_value(volatile size_t n) { volatile size_t v = n; return v; }
const char content[8] = "ZZZZZZZ";

// types

// globals

__attribute__((section(".data.index"))) volatile ssize_t i = 0;

__attribute__((noinline)) int f()
{
  // locals

  volatile char origin[8] = "";

  origin[0] = 0xAA;
  origin[1] = 0xAA;
  origin[2] = 0xAA;
  origin[3] = 0xAA;
  origin[4] = 0xAA;
  origin[5] = 0xAA;
  origin[6] = 0xAA;
  origin[7] = 0xAA;
  _use(origin);
  _use_value(*origin);
  while( i < 0 )
  {
    volatile char read_value[1024];
    size_t step_distance = (0 > (1024 + i)) ? 1024 : 0 - i;
    memcpy((void *)read_value, (void *)&origin[i], _hide_value(step_distance));
    i += step_distance;
    _use(read_value);
    _use_value(*read_value);
  }
  volatile char read_value[1];
  memcpy( (void *)read_value, (void *)&origin[i], _hide_value(1));
  _use( read_value );
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
