/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: global
 * Target: global
 * Bug type: inter-object, linear OOBA, overflow
 * Access type: stdlib, write
 * Variant:
 *  - target declared after origin
 *  - distance is checked as is
 *  - target reached by using a index
 *  - target accessed by using auxiliary variables
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types

// globals

char origin[8] = {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA};
char target[8] = {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA};
__attribute__((section(".data.index"))) volatile ssize_t i = 0;
__attribute__((section(".data.index"))) volatile size_t step_distance;

int f()
{
  // locals


  _use(target);
  _use(origin);
  if ( !((ssize_t)(GET_ADDR_BITS(target) - GET_ADDR_BITS(origin)) >= 0) ) _exit(PRECONDITIONS_FAILED_VALUE);
  if ( GET_ADDR_BITS(&i) < GET_ADDR_BITS(target) && GET_ADDR_BITS(&i) > GET_ADDR_BITS(origin) ) _exit(PRECONDITIONS_FAILED_VALUE);
  if ( GET_ADDR_BITS(&step_distance) < GET_ADDR_BITS(target) && GET_ADDR_BITS(&step_distance) > GET_ADDR_BITS(origin) ) _exit(PRECONDITIONS_FAILED_VALUE);
  i = 0;
  while( GET_ADDR_BITS(&origin[i]) < GET_ADDR_BITS(target) )
  {
    step_distance = (GET_ADDR_BITS(target) > (1024 + GET_ADDR_BITS(&origin[i]))) ? 1024 : GET_ADDR_BITS(target) - GET_ADDR_BITS(&origin[i]);
    memset((void *)&origin[i], 0xFF, step_distance);
    i += step_distance;
    _use(&origin[i]);
  }
  _use(origin);
  volatile size_t size = 8;
  memset( (void *)&origin[i], 0xFF, size);
  _use(&origin[i]);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
