/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: heap
 * Target: heap
 * Bug type: non-object, linear OOBA, underflow
 * Access type: direct, read
 * Variant:
 *  - distance is checked as is
 *  - target reached by using a index
 *  - target accessed by using constants
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types

// globals

__attribute__((section(".data.index"))) volatile char tmp;
__attribute__((section(".data.index"))) volatile size_t i;
__attribute__((section(".data.index"))) volatile ssize_t reach_index = 0;

int f()
{
  // locals


  char *origin = (char *)malloc( 8 );
  origin[0] = 0xAA;
  origin[1] = 0xAA;
  origin[2] = 0xAA;
  origin[3] = 0xAA;
  origin[4] = 0xAA;
  origin[5] = 0xAA;
  origin[6] = 0xAA;
  origin[7] = 0xAA;
  _use((origin - 1));
  _use(origin);
  if ( !(-1 <= 0) ) _exit(PRECONDITIONS_FAILED_VALUE);
  while( GET_ADDR_BITS(&origin[reach_index]) != GET_ADDR_BITS((origin - 1)) )
  {
    tmp = origin[reach_index];
    --reach_index;
    _use(&tmp);
  }
  volatile char read_value[1];
  volatile size_t i;
  for (i = 0; i < 1; i++)
  {
    read_value[i] = (origin + reach_index)[i];
  }
  _use(read_value);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  free(origin);
  return 0;
}

int main()
{
  f();

  return 0;
}
