/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: stack
 * Target: stack
 * Bug type: intra-object, linear OOBA, overflow
 * Access type: direct, write
 * Variant:
 *  - target declared before origin
 *  - distance is negated before checking
 *  - target reached by using a index
 *  - target accessed by using constants
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types
struct T
{
  char target[8];
  char origin[8];
};

// globals

__attribute__((section(".data.index"))) ssize_t reach_index = 0;

int f()
{
  // locals

  struct T s;

  s.target[0] = 0xAA;
  s.target[1] = 0xAA;
  s.target[2] = 0xAA;
  s.target[3] = 0xAA;
  s.target[4] = 0xAA;
  s.target[5] = 0xAA;
  s.target[6] = 0xAA;
  s.target[7] = 0xAA;
  s.origin[0] = 0xBB;
  s.origin[1] = 0xBB;
  s.origin[2] = 0xBB;
  s.origin[3] = 0xBB;
  s.origin[4] = 0xBB;
  s.origin[5] = 0xBB;
  s.origin[6] = 0xBB;
  s.origin[7] = 0xBB;
  _use(s.target);
  _use(s.origin);
  if ( GET_ADDR_BITS(&reach_index) < GET_ADDR_BITS(s.target) && GET_ADDR_BITS(&reach_index) > GET_ADDR_BITS(s.origin) ) _exit(PRECONDITIONS_FAILED_VALUE);
  if ( !(-(ssize_t)(GET_ADDR_BITS(s.origin) - GET_ADDR_BITS(s.target)) >= 0) ) _exit(PRECONDITIONS_FAILED_VALUE);
  while( GET_ADDR_BITS(&s.origin[reach_index]) != GET_ADDR_BITS(s.target) )
  {
    s.origin[reach_index] = 0xFF;
    ++reach_index;
    _use(&s.origin[reach_index]);
  }
  volatile size_t i;
  for (i = 0; i < 8; i++)
  {
    (s.origin + reach_index)[i] = 0xFF;
  }
  _use((s.origin + reach_index));
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
