/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: heap
 * Target: stack
 * Bug type: inter-object, linear OOBA, overflow
 * Access type: stdlib, read
 * Variant: target declared after origin, distance is checked as it is, target reached by stdlib reading using an auxiliary pointer, target accessed by stdlib reading using constants
 */

#include <unistd.h> // _exit
#include <stdint.h> // SIZE_MAX
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types

// globals

volatile char * aux_ptr;
volatile size_t i = 0;

int f()
{
  // locals

  char target[8] = "";

  char *origin = (char *)malloc( 8 );
  origin[0] = 0xAA;
  origin[1] = 0xAA;
  origin[2] = 0xAA;
  origin[3] = 0xAA;
  origin[4] = 0xAA;
  origin[5] = 0xAA;
  origin[6] = 0xAA;
  origin[7] = 0xAA;
  target[0] = 0xAA;
  target[1] = 0xAA;
  target[2] = 0xAA;
  target[3] = 0xAA;
  target[4] = 0xAA;
  target[5] = 0xAA;
  target[6] = 0xAA;
  target[7] = 0xAA;
  _use(target);
  _use(origin);
  if ( !((ssize_t)(GET_ADDR_BITS(target) - GET_ADDR_BITS(origin)) >= 0) ) _exit(PRECONDITIONS_FAILED_VALUE);
  aux_ptr = origin;
  while( i < (ssize_t)(GET_ADDR_BITS(target) - GET_ADDR_BITS(origin)) )
  {
    volatile char read_value[1024];
    size_t step_distance = ((ssize_t)(GET_ADDR_BITS(target) - GET_ADDR_BITS(origin)) > (1024 + i)) ? 1024 : (ssize_t)(GET_ADDR_BITS(target) - GET_ADDR_BITS(origin)) - i;
    memcpy((void *)read_value, (void *)aux_ptr, step_distance);
    aux_ptr += step_distance;
    i += step_distance;
    _use(&read_value);
  }
  volatile char read_value[8];
  memcpy( (void *)read_value, (void *)aux_ptr, 8);
  _use( read_value );
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  free(origin);
  return 0;
}

int main()
{
  f();

  return 0;
}
