/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: heap
 * Target: heap
 * Bug type: non-object, linear OOBA, underflow
 * Access type: direct, write
 * Variant:
 *  - target reached using global index
 */

#include <unistd.h> // _exit
#include <stdint.h> // SIZE_MAX
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types

// globals

__attribute__((section(".data.index"))) ssize_t reach_index = 0;

int f()
{
  // locals


  char *origin = (char *)malloc( 8 );
  origin[0] = 0xAA;
  origin[1] = 0xAA;
  origin[2] = 0xAA;
  origin[3] = 0xAA;
  origin[4] = 0xAA;
  origin[5] = 0xAA;
  origin[6] = 0xAA;
  origin[7] = 0xAA;
  _use(origin);
  while( GET_ADDR_BITS(&origin[reach_index]) != GET_ADDR_BITS(origin) )
  {
    origin[reach_index] = 0xFF;
    --reach_index;
    _use(&origin[reach_index]);
  }
  volatile size_t i;
  for (i = 0; i < 1; i++)
  {
    (origin + reach_index)[i] = 0xFF;
  }
  _use((origin + reach_index));
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  free(origin);
  return 0;
}

int main()
{
  f();

  return 0;
}
