/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: stack
 * Target: stack
 * Bug type: inter-object, linear OOBA, overflow
 * Access type: stdlib, write
 * Variant:
 *  - target declared before origin
 *  - distance is checked as is
 *  - target reached by using a stack auxiliary pointer, declared first
 *  - target accessed by using auxiliary variables
 */

#include <unistd.h> // _exit
#include <stdint.h> // SIZE_MAX
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types

// globals


int f()
{
  // locals
  volatile size_t step_distance;
  volatile char * aux_ptr;

  char target[8] = "";
  char origin[8] = "";

  target[0] = 0xAA;
  target[1] = 0xAA;
  target[2] = 0xAA;
  target[3] = 0xAA;
  target[4] = 0xAA;
  target[5] = 0xAA;
  target[6] = 0xAA;
  target[7] = 0xAA;
  origin[0] = 0xAA;
  origin[1] = 0xAA;
  origin[2] = 0xAA;
  origin[3] = 0xAA;
  origin[4] = 0xAA;
  origin[5] = 0xAA;
  origin[6] = 0xAA;
  origin[7] = 0xAA;
  _use(target);
  _use(origin);
  if ( GET_ADDR_BITS(&aux_ptr) < GET_ADDR_BITS(target) && GET_ADDR_BITS(&aux_ptr) > GET_ADDR_BITS(origin) ) _exit(PRECONDITIONS_FAILED_VALUE);
  if ( GET_ADDR_BITS(&step_distance) < GET_ADDR_BITS(target) && GET_ADDR_BITS(&step_distance) > GET_ADDR_BITS(origin) ) _exit(PRECONDITIONS_FAILED_VALUE);
  if ( !((ssize_t)(GET_ADDR_BITS(target) - GET_ADDR_BITS(origin)) >= 0) ) _exit(PRECONDITIONS_FAILED_VALUE);
  aux_ptr = origin;
  while( GET_ADDR_BITS(aux_ptr) < GET_ADDR_BITS(target) )
  {
    step_distance = (GET_ADDR_BITS(target) > (1024 + GET_ADDR_BITS(aux_ptr))) ? 1024 : GET_ADDR_BITS(target) - GET_ADDR_BITS(aux_ptr);
    memset((void *)aux_ptr, 0xFF, step_distance);
    aux_ptr += step_distance;
    _use(aux_ptr);
  }
  _use(origin);
  volatile size_t size = 8;
  memset( (void *)aux_ptr, 0xFF, size);
  _use(aux_ptr);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
