/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: global
 * Target: global
 * Bug type: intra-object, linear OOBA, overflow
 * Access type: stdlib, write
 * Variant:
 *  - target declared before origin
 *  - distance is checked as is
 *  - target reached by using a global index, initialized, declared last
 *  - target accessed by using constants
 */

#include <unistd.h> // _exit
#include <stdint.h> // SIZE_MAX
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types
struct T
{
  char target[8];
  char origin[8];
};

// globals

struct T s = { {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA}, {0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB} };
volatile ssize_t i = 0;
volatile size_t step_distance = 0;

int f()
{
  // locals


  _use(s.target);
  _use(s.origin);
  if ( !((ssize_t)(GET_ADDR_BITS(s.target) - GET_ADDR_BITS(s.origin)) >= 0) ) _exit(PRECONDITIONS_FAILED_VALUE);
  if ( GET_ADDR_BITS(&i) < GET_ADDR_BITS(s.target) && GET_ADDR_BITS(&i) > GET_ADDR_BITS(s.origin) ) _exit(PRECONDITIONS_FAILED_VALUE);
  if ( GET_ADDR_BITS(&step_distance) < GET_ADDR_BITS(s.target) && GET_ADDR_BITS(&step_distance) > GET_ADDR_BITS(s.origin) ) _exit(PRECONDITIONS_FAILED_VALUE);
  i = 0;
  while( GET_ADDR_BITS(&s.origin[i]) < GET_ADDR_BITS(s.target) )
  {
    step_distance = (GET_ADDR_BITS(s.target) > (1024 + GET_ADDR_BITS(&s.origin[i]))) ? 1024 : GET_ADDR_BITS(s.target) - GET_ADDR_BITS(&s.origin[i]);
    memset((void *)&s.origin[i], 0xFF, step_distance);
    i += step_distance;
    _use(&s.origin[i]);
  }
  _use(s.origin);
  memset( (void *)&s.origin[i], 0xFF, 8);
  _use(&s.origin[i]);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
