/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.3.
 */

/*
 * Memory region: heap
 * Bug type: misuse-of-free, used-memory
 * Access type: direct, write
 * Variant:
 *  - magic value 0x20
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

__attribute__((section(".data.index"))) volatile size_t _sink;
volatile void *_use(volatile void *p) { _sink = (size_t)p; return p; }
volatile long long _use_value(volatile long long p) { return p; }
__attribute__((noinline)) static size_t _hide_value(volatile size_t n) { volatile size_t v = n; return v; }
const char content[8] = "ZZZZZZZ";

// types

// globals

char* heap_obj;

__attribute__((noinline)) int f()
{
  // locals


  volatile char *target = (char *)malloc( 160 );
  
  #ifndef __GLIBC__
  _exit(PRECONDITIONS_FAILED_VALUE); // not using glibc
  #endif
  for (size_t i = 0; i < 16; i++) target[i] = 0;
  target[8] = 0x20; // magic value
  target[13*8] = 0x40;
  unsigned long *crafted_ptr;
  crafted_ptr = (unsigned long *)&(target[2*8]); // pointing at byte 0x10, content of chunk 0
  (void)malloc(8);
  free(crafted_ptr);
  
  heap_obj = (char *)malloc(8);
  volatile size_t i;
  for (i = 0; i < 8; i++)
  {
    heap_obj[i] = 0xFF;
    _use(&heap_obj[i]);
  }
  _use(heap_obj);
  _use_value(*heap_obj);
  exit(TEST_CASE_SUCCESSFUL_VALUE);

  free( (void *)target );
  return 0;
}

int main()
{
  f();

  return 0;
}
