/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Memory region: global
 * Bug type: misuse-of-free, used-memory
 * Access type: direct, read
 * Variant:
 *  - magic value 0x40
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types

// globals

char target[160];
char* heap_obj;

int f()
{
  // locals


  #ifndef __GLIBC__
  exit(PRECONDITIONS_FAILED_VALUE); // not using glibc
  #endif
  for (size_t i = 0; i < 16; i++) target[i] = 0;
  target[8] = 0x40; // magic value
  target[13*8] = 0x40;
  unsigned long *crafted_ptr;
  crafted_ptr = (unsigned long *)&(target[2*8]); // pointing at byte 0x10, content of chunk 0
  (void)malloc(8);
  free(crafted_ptr);
  
  heap_obj = (char *)malloc(8);
  volatile char read_value[8];
  volatile size_t i;
  for (i = 0; i < 8; i++)
  {
    read_value[i] = heap_obj[i];
  }
  _use(read_value);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
