/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.3.
 */

/*
 * Origin: global
 * Target: heap
 * Bug type: inter-object, non-linear OOBA, overflow
 * Access type: stdlib, read
 * Variant:
 *  - target declared after origin
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

__attribute__((section(".data.index"))) volatile size_t _sink;
volatile void *_use(volatile void *p) { _sink = (size_t)p; return p; }
volatile long long _use_value(volatile long long p) { return p; }
__attribute__((noinline)) static size_t _hide_value(volatile size_t n) { volatile size_t v = n; return v; }
const char content[8] = "ZZZZZZZ";

// types

// globals

volatile char origin[8] = {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA};

__attribute__((noinline)) int f()
{
  // locals


  volatile char *target = (char *)malloc( 8 );
  target[0] = 0xAA;
  target[1] = 0xAA;
  target[2] = 0xAA;
  target[3] = 0xAA;
  target[4] = 0xAA;
  target[5] = 0xAA;
  target[6] = 0xAA;
  target[7] = 0xAA;
  char read_value[8];
  memcpy(read_value, (void *)&target[0], _hide_value(8));
  _use(read_value);_use_value(*read_value);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  free( (void *)target );
  return 0;
}

int main()
{
  f();

  return 0;
}
