/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.3.
 */

/*
 * Origin: stack
 * Target: stack
 * Bug type: intra-object, non-linear OOBA, overflow
 * Access type: direct, write
 * Variant:
 *  - target declared after origin
 *  - To avoid optimizations, index into the target, upper bound hidden
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

__attribute__((section(".data.index"))) volatile size_t _sink;
volatile void *_use(volatile void *p) { _sink = (size_t)p; return p; }
volatile long long _use_value(volatile long long p) { return p; }
__attribute__((noinline)) static size_t _hide_value(volatile size_t n) { volatile size_t v = n; return v; }
const char content[8] = "ZZZZZZZ";

// types
struct T
{
  volatile char origin[8];
  volatile char target[8];
};

// globals


__attribute__((noinline)) int f()
{
  // locals

  struct T s;

  s.origin[0] = 0xAA;
  s.origin[1] = 0xAA;
  s.origin[2] = 0xAA;
  s.origin[3] = 0xAA;
  s.origin[4] = 0xAA;
  s.origin[5] = 0xAA;
  s.origin[6] = 0xAA;
  s.origin[7] = 0xAA;
  s.target[0] = 0xBB;
  s.target[1] = 0xBB;
  s.target[2] = 0xBB;
  s.target[3] = 0xBB;
  s.target[4] = 0xBB;
  s.target[5] = 0xBB;
  s.target[6] = 0xBB;
  s.target[7] = 0xBB;
  // index into the target to prevent optimizations
  for (ssize_t i = 0; i < _hide_value(8); i++) { char tmp = s.target[i]; _use(&tmp);  }
  if ( !((ssize_t)(GET_ADDR_BITS(s.target) - GET_ADDR_BITS(s.origin)) >= 0) ) _exit(PRECONDITIONS_FAILED_VALUE);
  for (ssize_t i = 0; i < 8; i++)
  {
    s.origin[i + (ssize_t)(GET_ADDR_BITS(s.target) - GET_ADDR_BITS(s.origin))] = 0xFF;
    _use(&s.origin[i + (ssize_t)(GET_ADDR_BITS(s.target) - GET_ADDR_BITS(s.origin))]);
  }
  _use(s.origin);
  _use_value(*s.origin);
  
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
