/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: stack
 * Target: global
 * Bug type: inter-object, non-linear OOBA, underflow
 * Access type: direct, read
 * Variant:
 *  - target declared after origin
 *  - To avoid optimizations, index into the target, upper bound not hidden
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

__attribute__((section(".data.index"))) volatile size_t _sink;
volatile void *_use(volatile void *p) { _sink = (size_t)p; return p; }
volatile long long _use_value(volatile long long p) { return p; }
__attribute__((noinline)) static size_t _hide_value(volatile size_t n) { volatile size_t v = n; return v; }
const char content[8] = "ZZZZZZZ";

// types

// globals

volatile char target[8] = {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA};

__attribute__((noinline)) int f()
{
  // locals

  volatile char origin[8] = "";

  origin[0] = 0xAA;
  origin[1] = 0xAA;
  origin[2] = 0xAA;
  origin[3] = 0xAA;
  origin[4] = 0xAA;
  origin[5] = 0xAA;
  origin[6] = 0xAA;
  origin[7] = 0xAA;
   _use(target); _use_value(*target);
  // index into the target to prevent optimizations
  for (ssize_t i = 0; i < 8; i++) { char tmp = target[i]; _use(&tmp); _use_value(target[i]); }
   _use(target); _use_value(*target);
  if ( !((ssize_t)(GET_ADDR_BITS(target) - GET_ADDR_BITS(origin)) <= 0) ) _exit(PRECONDITIONS_FAILED_VALUE);
  volatile char read_value[8];
  for (ssize_t access_index = 0; access_index < 8; access_index++)
  {
    read_value[access_index] = origin[access_index + (ssize_t)(GET_ADDR_BITS(target) - GET_ADDR_BITS(origin))];
    _use(&read_value[access_index]);
  }
  _use(read_value);
  _use_value(*read_value);
  
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
