/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: heap
 * Target: heap
 * Bug type: intra-object, type confusion OOBA, overflow
 * Access type: direct, read
 * Variant:
 *  - target declared after origin
 *  - using load widening
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

__attribute__((section(".data.index"))) volatile size_t _sink;
volatile void *_use(volatile void *p) { _sink = (size_t)p; return p; }
volatile long long _use_value(volatile long long p) { return p; }
__attribute__((noinline)) static size_t _hide_value(volatile size_t n) { volatile size_t v = n; return v; }
const char content[8] = "ZZZZZZZ";

// types
struct T
{
  volatile char origin[8];
  volatile char target[8];
};

// globals


__attribute__((noinline)) int f()
{
  // locals


  struct T *s = (struct T *)malloc( sizeof(struct T) );
  s->origin[0] = 0xAA;
  s->origin[1] = 0xAA;
  s->origin[2] = 0xAA;
  s->origin[3] = 0xAA;
  s->origin[4] = 0xAA;
  s->origin[5] = 0xAA;
  s->origin[6] = 0xAA;
  s->origin[7] = 0xAA;
  s->target[0] = 0xBB;
  s->target[1] = 0xBB;
  s->target[2] = 0xBB;
  s->target[3] = 0xBB;
  s->target[4] = 0xBB;
  s->target[5] = 0xBB;
  s->target[6] = 0xBB;
  s->target[7] = 0xBB;
  if ( !((ssize_t)(GET_ADDR_BITS(s->target) - GET_ADDR_BITS(s->origin)) >= 0) ) _exit(PRECONDITIONS_FAILED_VALUE);
  if ( !((ssize_t)(GET_ADDR_BITS(s->target) - GET_ADDR_BITS(s->origin)) < (8 + 1) ) ) _exit(PRECONDITIONS_FAILED_VALUE);
  volatile uint32_t read_value;
  read_value = *((volatile uint32_t *)(s->origin + (_hide_value(8) - 3)));
  _use(&read_value);
  _use_value(read_value);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  free( (void *)s );
  return 0;
}

int main()
{
  f();

  return 0;
}
