/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: stack
 * Target: stack
 * Bug type: non-object, type confusion OOBA, overflow
 * Access type: direct, read
 * Variant:
 *  - using big structure cast
 *  - using a global index
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

__attribute__((section(".data.index"))) volatile size_t _sink;
volatile void *_use(volatile void *p) { _sink = (size_t)p; return p; }
volatile long long _use_value(volatile long long p) { return p; }
__attribute__((noinline)) static size_t _hide_value(volatile size_t n) { volatile size_t v = n; return v; }
const char content[8] = "ZZZZZZZ";

// types
struct BigType
{
  char buffer[MAX_OBJECT_SIZE];
};

// globals

__attribute__((section(".data.index"))) ssize_t i;

__attribute__((noinline)) int f()
{
  // locals

  volatile char origin[8] = "";

  origin[0] = 0xAA;
  origin[1] = 0xAA;
  origin[2] = 0xAA;
  origin[3] = 0xAA;
  origin[4] = 0xAA;
  origin[5] = 0xAA;
  origin[6] = 0xAA;
  origin[7] = 0xAA;
  if ( 8 > (MAX_OBJECT_SIZE) )
    _exit(PRECONDITIONS_FAILED_VALUE);
  volatile char tmp;
  for (i = 0; i < 8; i++)
  {
    tmp = ((struct BigType *)origin)->buffer[i];
    _use(&tmp);
  }
  _use(&tmp);
  _use_value(tmp);
  volatile char read_value[1];
  for (ssize_t access_index = 0; access_index < 1; access_index++)
  {
    read_value[access_index] = ((struct BigType *)origin)->buffer[access_index + 8];
    _use(&read_value[access_index]);
  }
  _use(read_value);
  _use_value(*read_value);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
