/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

#include <unistd.h> // _exit
#include <stdint.h> // SIZE_MAX
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types

// globals
static ssize_t i;

struct BigType
{
  char buffer[(size_t)1 << 27];
};

int f()
{
  // locals

  char origin[8] = "";

  origin[0] = 0xAA;
  origin[1] = 0xAA;
  origin[2] = 0xAA;
  origin[3] = 0xAA;
  origin[4] = 0xAA;
  origin[5] = 0xAA;
  origin[6] = 0xAA;
  origin[7] = 0xAA;
  if ( (8 > 0 && 8 > ((size_t)1 << 27))
       || (8 < 0 && 8< -((size_t)1 << 27) ) )  _exit(PRECONDITIONS_FAILED_VALUE);
  if ( !(8 >= 0) ) _exit(PRECONDITIONS_FAILED_VALUE);
  volatile char tmp;
  for (i = 0; i < 8; i++)
  {
    tmp = ((struct BigType *)origin)->buffer[i];
  }
  _use(&tmp);
  volatile char read_value[1];
  for (ssize_t access_index = 0; access_index < 1; access_index++)
  {
    read_value[access_index] = ((struct BigType *)origin)->buffer[access_index + 8];
  }
  _use(read_value);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
