/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: stack
 * Target: stack
 * Bug type: non-object, type confusion OOBA, overflow
 * Access type: direct, write
 * Variant:
 *  - using big structure cast
 *  - using a global index
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

__attribute__((section(".data.index"))) volatile size_t _sink;
volatile void *_use(volatile void *p) { _sink = (size_t)p; return p; }
volatile long long _use_value(volatile long long p) { return p; }
__attribute__((noinline)) static size_t _hide_value(volatile size_t n) { volatile size_t v = n; return v; }
const char content[8] = "ZZZZZZZ";

// types
struct BigType
{
  char buffer[MAX_OBJECT_SIZE];
};

// globals

__attribute__((section(".data.index"))) ssize_t i;

__attribute__((noinline)) int f()
{
  // locals

  volatile char origin[8] = "";

  origin[0] = 0xAA;
  origin[1] = 0xAA;
  origin[2] = 0xAA;
  origin[3] = 0xAA;
  origin[4] = 0xAA;
  origin[5] = 0xAA;
  origin[6] = 0xAA;
  origin[7] = 0xAA;
  if ( 8 > (MAX_OBJECT_SIZE) )
    _exit(PRECONDITIONS_FAILED_VALUE);
  if ( GET_ADDR_BITS(&i) < GET_ADDR_BITS(&((struct BigType *)origin)->buffer[8]) && GET_ADDR_BITS(&i) > GET_ADDR_BITS(&((struct BigType *)origin)->buffer[0]) ) _exit(PRECONDITIONS_FAILED_VALUE);
  for (i = 0; i < 8; i++)
  {
    ((struct BigType *)origin)->buffer[i] = 0xFF;
    _use(&((struct BigType *)origin)->buffer[i]);
  }
  _use(((struct BigType *)origin)->buffer);
  _use_value(*((struct BigType *)origin)->buffer);
  for (ssize_t i = 0; i < 1; i++)
  {
    ((struct BigType *)origin)->buffer[i + 8] = 0xFF;
    _use(&((struct BigType *)origin)->buffer[i + 8]);
  }
  _use(((struct BigType *)origin)->buffer);
  _use_value(*((struct BigType *)origin)->buffer);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
