/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Origin: global
 * Target: global
 * Bug type: non-object, type confusion OOBA, overflow
 * Access type: direct, read
 * Variant:
 *  - using load widening
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types

// globals

char origin[8] = {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA};

int f()
{
  // locals


  volatile uint8_t read_value;
  read_value = *((volatile uint8_t *)(origin + (4 - 1)));
  _use(&read_value);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}

int main()
{
  f();

  return 0;
}
