/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.3.
 */

/*
 * Variant:
 *  - with repeated attempts
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

__attribute__((section(".data.index"))) volatile size_t _sink;
volatile void *_use(volatile void *p) { _sink = (size_t)p; return p; }
volatile long long _use_value(volatile long long p) { return p; }
__attribute__((noinline)) static size_t _hide_value(volatile size_t n) { volatile size_t v = n; return v; }
const char content[8] = "ZZZZZZZ";

// types

// globals

char *target_address;

__attribute__((noinline)) int f()
{
  // locals


  volatile char *target = (char *)malloc( 8 );
  
  target_address = (char *)&target[0];
  volatile char *reallocated = (char *)malloc( 8 );

  size_t counter = 0;
  while ( counter < 100)
  {
    free( (void *)reallocated );
    reallocated = (char *)malloc( 8 );
    reallocated[0] = 0xAA;
    reallocated[1] = 0xAA;
    reallocated[2] = 0xAA;
    reallocated[3] = 0xAA;
    reallocated[4] = 0xAA;
    reallocated[5] = 0xAA;
    reallocated[6] = 0xAA;
    reallocated[7] = 0xAA;
  
    counter++;
  }
  volatile char read_value[8];
  volatile size_t i;
  for (i = 0; i < 8; i++)
  {
    read_value[i] = target_address[i];
    _use(&target_address[i]);
  }
  _use(read_value);
  _use_value(*read_value);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  free( (void *)target );
  free( (void *)reallocated );
  return 0;
}

int main()
{
  f();

  return 0;
}
