/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.3.
 */

/*
 * Variant:
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

__attribute__((section(".data.index"))) volatile size_t _sink;
volatile void *_use(volatile void *p) { _sink = (size_t)p; return p; }
volatile long long _use_value(volatile long long p) { return p; }
__attribute__((noinline)) static size_t _hide_value(volatile size_t n) { volatile size_t v = n; return v; }
const char content[8] = "ZZZZZZZ";

// types

// globals

char *target_address;

__attribute__((noinline)) int other_f()
{
  volatile char reallocated[8];
  if (GET_ADDR_BITS(&reallocated[0]) != GET_ADDR_BITS(target_address)) _exit(PRECONDITIONS_FAILED_VALUE);
  memset( (void *)target_address, 0xFF, 8);
  _use(target_address);
  _use(reallocated);
  _use_value(*reallocated);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}
__attribute__((noinline)) int f()
{
  // locals

  volatile char target[8] = "";

  target[0] = 0xAA;
  target[1] = 0xAA;
  target[2] = 0xAA;
  target[3] = 0xAA;
  target[4] = 0xAA;
  target[5] = 0xAA;
  target[6] = 0xAA;
  target[7] = 0xAA;
  target_address = (char *)&target[0];

  return 0;
}

int main()
{
  f();
  other_f();

  return 0;
}
