/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Variant:
 *  - with repeated attempts
 *  - using an array of objects
 */

#include <unistd.h> // _exit
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif
#ifndef MAX_OBJECT_SIZE
#define MAX_OBJECT_SIZE ((size_t)1 << 29)
#endif

__attribute__((section(".data.index"))) volatile size_t _sink;
volatile void *_use(volatile void *p) { _sink = (size_t)p; return p; }
volatile long long _use_value(volatile long long p) { return p; }
__attribute__((noinline)) static size_t _hide_value(volatile size_t n) { volatile size_t v = n; return v; }
const char content[8] = "ZZZZZZZ";

// types

// globals

char *target_addresses[16];
char *last_address = NULL;
volatile char read_value[8];
int counter = 0;

__attribute__((noinline)) int other_f()
{
  volatile char reallocated[8];
  if ( GET_ADDR_BITS(last_address) == GET_ADDR_BITS(&reallocated[0]) ) _exit(PRECONDITIONS_FAILED_VALUE); // repeating does not help
  int counter;
  for (counter = 0; counter < 16; counter++)
  {
    if ( GET_ADDR_BITS(&reallocated[0]) == GET_ADDR_BITS(target_addresses[counter]) ) break;
  }
  if (counter == 16) _exit(PRECONDITIONS_FAILED_VALUE);
  memcpy( (void *)read_value, (void *)target_addresses[counter], _hide_value(8));
  _use( read_value );
  return TEST_CASE_SUCCESSFUL_VALUE;

  return 0;
}
__attribute__((noinline)) int f()
{
  // locals


  volatile char target[16][8];
  for (int i = 0; i < 16; i++)
  {
    target[i][0] = 0xAA;
    target[i][1] = 0xAA;
    target[i][2] = 0xAA;
    target[i][3] = 0xAA;
    target[i][4] = 0xAA;
    target[i][5] = 0xAA;
    target[i][6] = 0xAA;
    target[i][7] = 0xAA;
  }
  for (int counter = 0; counter < 16; counter++) target_addresses[counter] = (char *)&target[counter][0];

  return 0;
}

int main()
{
  f();
  do
  {
    (void)  other_f();
  } while (counter++ < 1000000000);
  _exit(PRECONDITIONS_FAILED_VALUE);

  return 0;
}
