/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

/*
 * Variant:
 *  - using an array of objects
 */

#include <unistd.h> // _exit
#include <stdint.h> // SIZE_MAX
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types

// globals

char *target_addresses[16];
volatile char read_value[8];
volatile size_t i;

int other_f()
{
  char reallocated[8];
  int counter;
  for (counter = 0; counter < 16; counter++)
  {
    if ( GET_ADDR_BITS(&reallocated[0]) == GET_ADDR_BITS(target_addresses[counter]) ) break;
  }
  if (counter == 16) _exit(PRECONDITIONS_FAILED_VALUE);
  for (i = 0; i < 8; i++)
  {
    read_value[i] = target_addresses[counter][i];
  }
  _use(read_value);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}
int f()
{
  // locals


  char target[16][8];
  for (int i = 0; i < 16; i++)
  {
    target[i][0] = 0xAA;
    target[i][1] = 0xAA;
    target[i][2] = 0xAA;
    target[i][3] = 0xAA;
    target[i][4] = 0xAA;
    target[i][5] = 0xAA;
    target[i][6] = 0xAA;
    target[i][7] = 0xAA;
  }
  for (int counter = 0; counter < 16; counter++) target_addresses[counter] = &target[counter][0];

  return 0;
}

int main()
{
  f();
  other_f();

  return 0;
}
