/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.1.
 */

#include <unistd.h> // _exit
#include <stdint.h> // SIZE_MAX
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types

// globals

char *target_address;
int counter = 0;
char *last_address = NULL;
volatile char read_value[8];
volatile size_t i;

int other_f()
{
  char reallocated[8];
  if (GET_ADDR_BITS(last_address) == GET_ADDR_BITS(&reallocated[0])) _exit(PRECONDITIONS_FAILED_VALUE); // repeating does not help
  last_address = &reallocated[0];
  if (GET_ADDR_BITS(&reallocated[0]) != GET_ADDR_BITS(target_address)) return PRECONDITIONS_FAILED_VALUE;
  for (i = 0; i < 8; i++)
  {
    read_value[i] = target_address[i];
  }
  _use(read_value);
  _exit(TEST_CASE_SUCCESSFUL_VALUE);

  return 0;
}
int f()
{
  // locals

  char target[8] = "";

  target[0] = 0xAA;
  target[1] = 0xAA;
  target[2] = 0xAA;
  target[3] = 0xAA;
  target[4] = 0xAA;
  target[5] = 0xAA;
  target[6] = 0xAA;
  target[7] = 0xAA;
  target_address = &target[0];

  return 0;
}

int main()
{
  f();
  do
  {
    (void)  other_f();
  } while (counter++ < 1000000000);
  _exit(PRECONDITIONS_FAILED_VALUE);

  return 0;
}
