/*
 * This file is distributed under the Apache License, Version 2.0; refer to
 * LICENSE for details.
 *
 * Generated by MSET 1.0.
 */

#include <unistd.h> // _exit
#include <stdint.h> // SIZE_MAX
#include <stdlib.h>
#include <string.h>

#ifdef ADDR_MASK
#define GET_ADDR_BITS(p) ((size_t)(p) & ADDR_MASK)
#else
#define GET_ADDR_BITS(p) ((size_t)(p) & (size_t)0xffffffffffffull)
#endif

volatile void *_use(volatile void *p) { return p; }
const char content[8] = "ZZZZZZZ";

// types

// globals

char *target_addresses[16];
char *last_address = NULL;
static int var_size = 8;
int counter = 0;

int other_f()
{
  char reallocated[8];
  if ( GET_ADDR_BITS(last_address) == GET_ADDR_BITS(&reallocated[0]) ) _exit(PRECONDITIONS_FAILED_VALUE); // repeating does not help
  int i;
  for (i = 0; i < 16; i++)
  {
    if ( GET_ADDR_BITS(&reallocated[0]) == GET_ADDR_BITS(target_addresses[i]) ) break;
  }
  if (i == 16) _exit(PRECONDITIONS_FAILED_VALUE);
  memcpy( target_addresses[i], content, var_size);
  _use(target_addresses[i]);
  return TEST_CASE_SUCCESSFUL_VALUE;

  return 0;
}
int f()
{
  // locals


  char target[16][8];
  for (int i = 0; i < 16; i++)
  {
    target[i][0] = 0xAA;
    target[i][1] = 0xAA;
    target[i][2] = 0xAA;
    target[i][3] = 0xAA;
    target[i][4] = 0xAA;
    target[i][5] = 0xAA;
    target[i][6] = 0xAA;
    target[i][7] = 0xAA;
  }
  for (int i = 0; i < 16; i++) target_addresses[i] = &target[i][0];

  return 0;
}

int main()
{
  f();
  do
  {
    (void)  other_f();
  } while (counter++ < 1000000000);
  _exit(PRECONDITIONS_FAILED_VALUE);

  return 0;
}
